# Orchestrator Service Configuration
# This file defines the endpoints and settings for the API orchestrator
# 
# Authentication: This service acts as a transparent proxy that forwards 
# authentication headers to backend services. Each backend service handles
# its own authentication - the orchestrator does not validate tokens.

# List of endpoints to register and manage
endpoints:
  # HTTPBin service for testing GET requests
  - url: "https://httpbin.org/get"
    name: "httpbin_get"
    version: "v1"
    methods: ["GET"]
    auth_type: "none"  # Documentation only - indicates backend expects no auth
    disabled: false
    health_check_path: "/get"
    timeout: 30

  # HTTPBin service for testing POST requests  
  - url: "https://httpbin.org/post"
    name: "httpbin_post"
    version: "v1"
    methods: ["POST"]
    auth_type: "none"  # Documentation only - indicates backend expects no auth
    disabled: false
    health_check_path: "/post"
    timeout: 30

  # JSONPlaceholder API for testing
  - url: "https://jsonplaceholder.typicode.com/posts"
    name: "jsonplaceholder_posts"
    version: "v1"
    methods: ["GET", "POST"]
    auth_type: "none"  # Documentation only - indicates backend expects no auth
    disabled: false
    timeout: 30

  # Example of a disabled endpoint
  - url: "https://api.example.com/v1/users"
    name: "example_users"
    version: "v1"
    methods: ["GET", "POST", "PUT", "DELETE"]
    auth_type: "bearer"  # Documentation only - indicates backend expects Bearer token
    disabled: true
    health_check_path: "/health"
    timeout: 45

# Circuit breaker configuration
circuit_breaker:
  failure_threshold: 5          # Number of consecutive failures to trip circuit
  reset_timeout: 60            # Seconds before attempting to reset circuit
  half_open_max_calls: 3       # Max calls allowed in half-open state
  fallback_strategy: "error_response"

# Health check configuration  
health_check:
  enabled: true               # Enable/disable health checks
  interval: 30                # Health check interval in seconds
  timeout: 10                 # Health check timeout in seconds
  unhealthy_threshold: 3      # Consecutive failures to mark unhealthy
  healthy_threshold: 2        # Consecutive successes to mark healthy

# General settings
log_level: "INFO"             # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL